[build]
  command = "npm install && npm run build"
  publish = "dist/frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  API_URL = "https://stunning-tulumba-f90485.netlify.app/api"
  GRAPHQL_URL = "https://stunning-tulumba-f90485.netlify.app/graphql"
  SOCKET_URL = "https://stunning-tulumba-f90485.netlify.app/" 