[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  API_URL = "https://your-backend-url.netlify.app/api"
  GRAPHQL_URL = "https://your-backend-url.netlify.app/graphql"
  SOCKET_URL = "https://your-backend-url.netlify.app" 