[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  publish = "dist/frontend"
  base = "frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 