[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[build.environment]
  NODE_VERSION = "18" 