[build]
  command = "npm install && prisma generate"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"
  PRISMA_CLIENT_ENGINE_TYPE = "binary" 