[build]
  command = "npm install && npx prisma generate"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@prisma/client",
    "graphql",
    "apollo-server-lambda",
    "bcryptjs",
    "jsonwebtoken",
    "cors",
    "dotenv"
  ]

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"
  PRISMA_CLIENT_ENGINE_TYPE = "binary"
  PRISMA_SCHEMA_PATH = "prisma/schema.prisma" 